<font color='orange' size=8><B>**Homework Assignment 2: Differential Kinematics**</B></font>

<font size=5><B>Objective :</B></font>

การบ้านนี้ถูกออกแบบมาเพื่อให้ผู้เรียนสามารถประยุกต์องค์ความรู้การหาจลนศาสตร์เชิงอนุพันธ์ (Differential kinematics) ของหุ่นยนต์แขนกล 3 แกน (3-DOF Manipulator)


จากการศึกษาในหลายอาทิตย์ที่ผ่านมา นักศึกษาสามารถประยุกต์ความรู้ในเรื่องของการหาจลศาสตร์เชิงอนุพันธ์เพื่อใช้ในการควบคุมหุ่นยนต์ RRR ที่มีลักษณะโครงสร้างดังรูปที่ 1 โดยใช้สมการ Forward Kinematics ที่ทางผู้ผลิดให้มาในฟังก์ชัน FKHW2(q) ในไฟล์ HW2_utilis.py

![img](pic1.png)

รูปที่ 1 การวางเฟรมของหุ่นยนต์ RRR (แกนในระบบสามมิติ สีแดงคือแกน X และสีน้ำเงินคือแกน Z) โดยที่

> $\mathbf{d_{1}} = 0.0892$ [m] <br>
> $\mathbf{a_{2}} = -0.425$ [m] <br>
> $\mathbf{r_{3,e}^{3}} = [0, -{\pi\over 2},0]$ [rad] (roll - pitch - yaw) <br>
> $\mathbf{p_{3,e}^{3}} = [-0.4744, -0.0930, 0.1090]$


In [ ]:
# ตัวอย้างการใช้งานฟังก์ชัน FKHW2
from HW2_utils_doc import FKHW2
import numpy as np

q = [6.043218569544089,3.6136940157364594,0.21539221741744516]
#q =[0,0,0]
#q = [0.17987944849976847, 1.4025733527756756, 3.3870501158703457]
R,P,R_e,p_e = FKHW2(q)
# print("H_0_e")
# print(R_e)
# print("------------------------")
# print("p_e")
# print(p_e)
# print("P")
# print(P[:,2],P[:,1],P[:,0])
# print(R)
# print(R[:,:,2])
# print(R[:,:,1])
# print(R[:,:,0])

homo0_1 = np.asarray(R[:,:,0])
homo0_2 = np.asarray(R[:,:,1])
homo0_3 = np.asarray(R[:,:,2])
homo0_end = np.asarray(R[:,:,3])
p1 = np.asarray(P[:,0])
p2 = np.asarray(P[:,1])
p3 = np.asarray(P[:,2])
pend = np.asarray(P[:,3])

z0 = np.array([0,0,1])
z1 = homo0_1[:,2]
z2 = homo0_2[:,2]
z3 = homo0_3[:,2]

# p1 = np.transpose([p1])
# p2 = np.transpose([p2])
# p3 = np.transpose([p3])
# pend = np.transpose([pend])
# z1 = np.transpose([z1])
# z2 = np.transpose([z2])
# z3 = np.transpose([z3])
J1 = [z1[0],z2[0],z3[0]]
J2 = [z1[1],z2[1],z3[1]]
J3 = [z1[2],z2[2],z3[2]]
J4 = [np.cross(z1, (pend-p1))[0],np.cross(z2, (pend-p2))[0], np.cross(z3, (pend-p3))[0]]
J5 = [np.cross(z1, (pend-p1))[1],np.cross(z2, (pend-p2))[1], np.cross(z3, (pend-p3))[1]]
J6 = [np.cross(z1, (pend-p1))[2],np.cross(z2, (pend-p2))[2], np.cross(z3, (pend-p3))[2]]

J = [J1,J2,J3,J4,J5,J6]
print(J)
#det = np.linalg.det(J)
#print(det)

w = [
    8.106841618092648,
    8.02219198687249,
    8.911653983433055,
    1.370778930335701,
    5.319200671072569,
    8.547756116934423
  ]

# homo0_1 = np.linalg.inv(homo0_1)
# homo0_2 = np.linalg.inv(homo0_2)
# homo0_3 = np.linalg.inv(homo0_3)

nend = np.transpose([[w[0],w[1],w[2]]])
fend = np.transpose([[w[3],w[4],w[5]]])
f0 = homo0_end @ fend
f1 = np.linalg.inv(homo0_1) @ f0
f2 = np.linalg.inv(homo0_2) @ f0
f3 = np.linalg.inv(homo0_3) @ f0

n0 = homo0_end @ nend
n1 = np.linalg.inv(homo0_1) @ n0
n2 = np.linalg.inv(homo0_2) @ n0
n3 = np.linalg.inv(homo0_3) @ n0

wj1 = np.array([n0[0],n0[1],n0[2],f0[0],f0[1],f0[2]])
wj2 = np.array([n0[0],n0[1],n0[2],f0[0],f0[1],f0[2]])
wj3 = np.array([n0[0],n0[1],n0[2],f0[0],f0[1],f0[2]])

J = np.transpose(J)
tua1 = J[:][0] @ wj1
tua2 = J[:][1] @ wj2
tua3 = J[:][2] @ wj3

tua = [[tua1[0], tua2[0], tua3[0]]]
#print(tua)
#print(homo0_1 @ f0)
#print(np.linalg.inv(homo0_1) @ f0)
#print(J@wj1)


: 


สมการ Forward Kinematics เขียนอยู่ในรูปของฟังก์ชันดังนี้

> ```python
>     R,P,R_e,p_e = FKHW2(q)
> ```
> เมื่อ <br>
>> $\mathbf{R}(:,:,i) = \mathbf{R}_{i}^{0}$ <br>
>> $\mathbf{P}(:,i) = \mathbf{p}_{0}^{0,i}$ <br>
>> $\mathbf{R}_{e} = \mathbf{R}_{e}^{0}$ <br>
>> $\mathbf{p}_{e} = \mathbf{p}_{0,e}^{0}$ <br>
>> $\mathbf{p}_{0,i}^{0} \in \mathbf{R}^{3 \times 1}$ เป็นเวกเตอร์หลักของ double ที่มีขนาดเท่ากับ 3 ที่แสดงถึงตำแหน่งของจุดกำเนิดของเฟรมพิกัด $\mathrm{F}_{i}$ ที่สัมพัทธ์กับจุดกำเนิดของเฟรมพิกัด $\mathrm{F}_{0}$ และอ้างอิงกับเฟรมพิกัด $F_{0}$ <br>
> $\mathbf{R}_{i}^{0} \in \mathbf{R}^{3 \times 3}$ เป็นเมตริกซ์การหมุนของ double ที่มีขนาดเท่ากับ 3x3 ที่แสดงถึงทิศทางหมุนของเฟรมพิกัด $\mathrm{F}_{i}$ ที่อ้างอิงกับเฟรมพิกัด $\mathrm{F}_{0}$ <br>
> $\mathrm{q} \in \mathrm{R}^{3}$ เป็นเวกเตอร์หลักของ double ที่มีขนาดเท่ากับ 3 ที่แสดงถึง configuration ของหุ่นยนต์ (Joint Configuration) <br>
> ```python
>      R,P,R_e,p_e = FKHW2([0,0,0])
>```




><br>
> <i><b>คำถามข้อที่ 1 </i></b><br>
> จงเขียนฟังก์ชันในการ Jacobian ของหุ่นยนต์ตัวนี้ให้อยู่ในฟังก์ชันต่อไปนี้ <br>
>
> ```python
> J_e = endEffectorJacobianHW2(q)
>```
> โดยที่ <br>
>>$\mathbf{J}_{e} \in \mathbf{R}^{6 \times 3}$ คือเมตริกซ์จาโคเบียนของเฟรมพิกัด $\mathrm{F}_{e}$ <br>
>>$\mathbf{q} \in \mathbf{R}_{3}$ เป็นเวกเตอร์หลักของ double ที่มีขนาดเท่ากับ 3 ที่แสดงถึง configuration ของหุ่นยนต์ (Joint Configuration) <br><br>
>><i><b>หมายเหตุ: </b></i><br>
>> $\mathbf{J_{\omega}^{(e)}} = \mathbf{J_{\omega}^{(n)}}$ <br>
>> $\mathbf{J_{v}^{(e)}} = \mathbf{J_{v}^{(n)} + S(R_{n}^{0}  p_{n,e}^{n})}$<br>
>
> <br>


> <i><b>คำถามที่ 2</b></i>
>
> กำหนดให้ Taskspace Variable เป็น $\mathbf{p_{0,e}^{0}} = \mathbf{[p_{x},p_{y},p_{z}]}$ ในการควบคุมแขนกล RRR พบว่ามีหลายตำแหน่งใน configuration space ที่จะทำให้เกิดสภาวะ Singularity ทำให้ไม่สามารถหา inverse velocity kinematics ของสมการได้ กำหนดให้หุ่นยนต์อยู่ในสภาวะ Sigularity ก็ต่อเมื่อ<br>
>
> $$ \mathbf{||det(J^{*}(q))|| < ε }$$
> <br>
>
>โดยที่ค่า &epsilon; มีค่า 0.001 จงเขียนฟังก์ชันในการหาสภาวะ Singularity
> ```python
>   flag = checkSingularityHW2(q)
> ```
>> $flag \in $ {True, False} เป็น bool ที่มีค่าเท่ากับ True ก็ต่อเมื่ออยู่ตำแหน่งใกล้สภาวะ Singularity หรือมีค่าเท่ากับ False เมื่อแขนกลอยู่ในสภาวะปกติ <br>
>> $\mathbf{q \in R^{3}}$ เป็นเวกเตอร์หลักของ double ที่มีขนาดเท่ากับ 3 ที่แสดงถึง configuration ของหุ่นยนต์ (Joint Configuration) <br>
>


In [74]:
q = [
        2.030701788674824,
        1.988805837665783,
        4.213698869804006
      ]
      
R,P,R_e,p_e = FKHW2(q)
homo0_1 = np.asarray(R[:,:,0])
homo0_2 = np.asarray(R[:,:,1])
homo0_3 = np.asarray(R[:,:,2])
p1 = np.asarray(P[:,0])
p2 = np.asarray(P[:,1])
p3 = np.asarray(P[:,2])
pend = np.asarray(P[:,3])
z1 = homo0_1[:,2]
z2 = homo0_2[:,2]
z3 = homo0_3[:,2]

J1 = [z1[0],z2[0],z3[0]]
J2 = [z1[1],z2[1],z3[1]]
J3 = [z1[2],z2[2],z3[2]]
J4 = [np.cross(z1, (pend-p1))[0],np.cross(z2, (pend-p2))[0], np.cross(z3, (pend-p3))[0]]
J5 = [np.cross(z1, (pend-p1))[1],np.cross(z2, (pend-p2))[1], np.cross(z3, (pend-p3))[1]]
J6 = [np.cross(z1, (pend-p1))[2],np.cross(z2, (pend-p2))[2], np.cross(z3, (pend-p3))[2]]

J = [J4,J5,J6]

J = np.asarray(J) 
print(J)

det = np.linalg.det(J)

if abs(det) < 0.001:
    flag = True
else:
    flag = False

print(abs(det),flag)

[[ 0.         -0.89609444 -0.89609444]
 [ 0.         -0.44386339 -0.44386339]
 [-0.22748736  0.19657319  0.02417355]]
0.0 True


> <br>
> <i><b> คำถามข้อที่ 3</b></i><br>
> ถ้าหากนักศึกษาติดตั้ง Force Sensor รุ่น FT300 ที่สามารถวัดแรงและแรงควบคู่ในพิกัดสามมิติ โดยติดตั้งในตำแหน่งกึ่งกลางปลายมือของหุ่นยนต์ RRR ในเฟรมพิกัด  สามารถอ่านค่าแรงได้จาก Sensor ดังนี้
>
> $$ w^{e} = \left\lbrack \matrix{n^{e} \cr f^{e}} \right\rbrack $$
>
> จงเขียนฟังก์ชันในการหาeffortของแต่ละข้อต่อเมื่อมี wrench มากระทำกับจุดกึ่งกลางของเฟรมพิกัด $F^{e}$
>```python
>   tau = computeEffortHW2(q,w)
>```
>$$\tau = computeEffort(q,w)$$
>> $\mathbf{tau \in R^{3}}$ เป็นเวกเตอร์หลักของ double ที่มีขนาดเท่ากับ 3 ที่แสดงถึงค่า Effort ของแต่ละข้อต่อ <br>
> $\mathbf{q \in R^{3}}$ เป็นเวกเตอร์หลักของ double ที่มีขนาดเท่ากับ 3 ที่แสดงถึง configuration ของหุ่นยนต์ (Joint Configuration)  <br>
> $\mathbf{w \in R^{6}}$ เป็นเวกเตอร์หลักของ double ที่มีขนาดเท่ากับ 6 ที่แสดงโมเมนท์และแรงที่อ้างอิงกับเฟรมพิกัด $\mathrm{F_{e}}$ <br>
>><i><b>หมายเหตุ: </b></i><br>
>>
>>$$ \mathbf{f^{A} = R_{B}^{A}\cdot f^{B}} $$
>>
>>$$ \mathbf{n^{A} = R_{B}^{A}\cdot n^{B}} $$
<br>


In [95]:
# ตัวอย่าง testcase สำหรับคำถามข้อที่ 1

{
  "q": [
        6.043218569544089,
        3.6136940157364594,
        0.21539221741744516
      ],
"j_e": [
        [
          0,
          0.23767031729221344,
          0.23767031729221344
        ],
        [
          0,
          0.9713459014892578,
          0.9713459014892578
        ],
        [
          1,
          6.123234262925839e-17,
          6.123234262925839e-17
        ],
        [
          -0.2689544845464035,
          0.5499962518288712,
          0.36226181412308617
        ],
        [
          -0.6405841185199471,
          -0.13457387680462826,
          -0.08863874359636544
        ],
        [
          0,
          0.686151255762767,
          0.3076400251861997
        ]
      ]
}

# ตัวอย่าง testcase สำหรับคำถามข้อที่ 2
{
  "q": [
        2.030701788674824,
        1.988805837665783,
        4.213698869804006
      ],
  "flag": True
}

#ตัวอย่าง testcase สำหรับคำถามข้อที่ 3
{
  "q": [
          0.17987944849976847,
          1.4025733527756756,
          3.3870501158703457
        ],
  "w": [
    8.106841618092648,
    8.02219198687249,
    8.911653983433055,
    1.370778930335701,
    5.319200671072569,
    8.547756116934423
  ],
  "tau": [
    10.285060525578045,
    6.098441929441673,
    4.788311882586214
  ]
}

{'q': [0.17987944849976847, 1.4025733527756756, 3.3870501158703457],
 'w': [8.106841618092648,
  8.02219198687249,
  8.911653983433055,
  1.370778930335701,
  5.319200671072569,
  8.547756116934423],
 'tau': [10.285060525578045, 6.098441929441673, 4.788311882586214]}

# ชนิดของตัวแปร

<b>ฟังก์ชัน endEffectorJacobianHW2(q)</b>
<br>q : input format list 1x3 [[i_11, i_12, i_13]]
<br>        q unit: rad
<br>J_e : return format list 6x3
<br>[ [i_11, i_12, i_13],
<br>    [i_21, i_22, i_23],
<br>    [i_31, i_32, i_33],
<br>    [i_41, i_42, i_43],
<br>    [i_51, i_52, i_53],
<br>    [i_61, i_62, i_63] ]

<b>ฟังก์ชัน checkSingularityHW2(q)</b>
<br>q : input format list 1x3 [[i_11, i_12, i_13]]
<br>        q unit: rad
<br>flag: return format bool

<b>ฟังก์ชัน manipulatorJacobian(q, w)</b>
<br>q : input format list 1x3 [[i_11, i_12, i_13]]
<br>w : input format list 1x6 [[i_11, i_12, i_13, i_14, i_15, i_16]]
<br>        i_11 = n_x  Moment ในแนวแกน x
<br>        i_12 = n_y  Moment ในแนวแกน y
<br>        i_13 = n_z  Moment ในแนวแกน z
<br>        i_14 = f_x  Force ในแนวแกน x
<br>        i_15 = f_y  Force ในแนวแกน y
<br>        i_16 = f_z  Force ในแนวแกน z
<br>tau : return format list 1x3 [[i_11, i_12, i_13]]
<br>        i_11 = effort ของ joint ที่ 1
<br>        i_12 = effort ของ joint ที่ 2
<br>        i_13 = effort ของ joint ที่ 3



## หมายเหตุ
> ไฟล์ที่มอบให้จะมีทั้งหมด 2 ไฟล์ 
<br>1. ไฟล์สำหรับเขียนคำตอบ ("fra333_hw2.py") 
<br>2. ไฟล์ตรวจคำตอบ ("testSctipt.py") ให้นักศึกษาเขียนคำตอบพร้อมทั้งเขียน comment อธิบายลงในไฟล์ .py ที่มอบให้และแก้ไขชื่อไฟล์ให้อยู่ใน format ตามที่กำหนด 
<br>3. ให้นักศึกษา zip ไฟล์ทั้งหมดเป็นไฟล์ชื่อ "fra333_hwx_xxxx_xxxx_v*.zip" ตัวอย่างเช่น ในกลุ่มประกอบไปด้วยนศ.รหัส 61340800001 61340800005 ไฟล์เวอร์ชัน 2 ดังนั้นชื่อไฟล์ คือ "fra333_hw2_6101_6105_v2.zip" 

## วิธีการตรวจคำตอบและให้คะแนน
> - Testcase ที่อาจารย์ให้ไปเป็นเพียง Guide สำหรับการตรวจเท่านั้น
> - นักศึกษาสามารถเช็คคำตอบจาก testcase ที่อาจารย์กำหนดให้
testcase ดังกล่าวอาศัยการเทียบค่าของคำตอบที่นักศึกษาหามาได้กับเฉลยของอาจารย์ <br>
> - ถ้านักศึกษาสามารถตรวจคำตอบใน testcase ถูกทุกกรณี นักศึกษาจะได้รับคะแนน 4/10 คะแนน<br>
> - ถ้านักศึกษา comment code พร้อมแสดงกระดาษทดในที่มาที่ไปของการเขียน code นักศึกษาจะได้คะแนน 6/10 คะแนน <br>